[project]
name = "freed"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "pyrefly>=0.60.2",
    "pytest>=9.0.2",
]

[tool.pyrefly]
search-path = [
    "Freed/src/",
    "Freed/Tests/"
]
project-includes = ["src", "Tests"]